name: Build .NET Core Project

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core SDK v3.1.301
      uses: actions/setup-dotnet@v1.5.0
      with:
        dotnet-version: 3.1.301
    - name: dotnet info
      run: dotnet --info
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build serverino.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
